const POUND_PER_MWH_TO_KILOGRAM_PER_KWH_MULTIPLIER = 0.000453592;

const GRID_OPTIONS = {
  'California': 'CAMX',
};

// lb / MWh
const TOTAL_OUTPUT_EF_CH4_BY_GRID = {
  'CAMX': 0.034,
}

// lb / MWh
const TOTAL_OUTPUT_EF_CO2_BY_GRID = {
  'CAMX': 496.5,
}

// lb / MWh
const TOTAL_OUTPUT_EF_N2O_BY_GRID = {
  'CAMX': 0.004,
}

module.exports = {
  GRID_OPTIONS,
  POUND_PER_MWH_TO_KILOGRAM_PER_KWH_MULTIPLIER,
  TOTAL_OUTPUT_EF_CH4_BY_GRID,
  TOTAL_OUTPUT_EF_CO2_BY_GRID,
  TOTAL_OUTPUT_EF_N2O_BY_GRID,
}
